+
DenisenkoMax/java-explore-with-me pull request #2
Opened 2022-11-15 15:07 UTC by DenisenkoMax

2022-11-25 17:21 UTC, damirovna requested changes
Сейчас я проверила:

1.  Работа со сборкой
2.  работа с докером
3.  струтуры БД
4.  модель данных
5.  Объектов DTO

**Нужно исправить работу с просмотрами и  внести правки в модель и объекты ДТО не только для события, но и аналогично для всех сущностей.**

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/model/Event.java
> +public class Event implements Serializable {
В этом классе и в остальных классах модели укажите, пожалуйста @Column(nullable = false) на полях, которые не могут быть null

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +public class EventShortDto {
Обратите внимание, что все поля этого класса дублируются в классе EventFullDto используйте наследование, чтобы избежать дублирования кода

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private int views;
Нужно добавить аннотацию @PositiveOrZero

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private int confirmedRequests;
Нужно добавить аннотацию @PositiveOrZero

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private String annotation;
Нужно добавить аннотацию @NotBlank

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private String title;
Нужно добавить аннотацию @NotBlank

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private CategoryDto category;
Нужно добавить аннотацию @NotNull

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private LocalDateTime eventDate;
Нужно добавить аннотацию @NotNull

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private UserShortDto initiator;
Нужно добавить аннотацию @NotNull

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String eventDate;
Лучше сделать другой тип:
```
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
	private final @NotNull @Future LocalDateTime eventDate;
```

Тгда мы сможем убедиться, что начало события в будущем.

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String annotation;
На строковые поля лучше навешивать @notblank

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private Integer participantLimit;
Нужно добавить @PositiveOrZero

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String title;
Нужно на это поле добавить @Size(min = 3, max = 120)
аналогично нужно ограничить поля annotation и description

2022-11-25 17:21 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private Long initiator;
а разве поля 

private Long initiator;
    private String state;
    private String createdOn;

Нужны в этом классе?

2022-11-26 05:19 UTC, DenisenkoMax commented on ewm-service/src/main/resources/schema.sql
> +    name VARCHAR(255)  NOT NULL
Выполнено

2022-11-26 05:23 UTC, DenisenkoMax commented on ewm-service/src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
Выполнено

2022-11-26 14:44 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/model/Event.java
> +public class Event implements Serializable {
Выполнено

2022-11-26 17:00 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +public class EventShortDto {
Спасибо! Не обратил внимание на избыточность кода, исправил)

2022-11-26 17:17 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String eventDate;
Спасибо! изначально и хотел забирать в LocalDateTime, но толком не разобрался в аннотациях. Теперь порядок!

2022-11-27 08:06 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String annotation;
Выполнено

2022-11-27 08:12 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private String title;
Выполнено

2022-11-27 08:13 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private Long initiator;
Не нужны, убрал

2022-11-27 12:50 UTC, DenisenkoMax commented on ewm-service/src/main/resources/schema.sql
> +    views INT,
Исправлено. Пришлось многое переписывать. Были вопросы по добавлению просмотров в списки с неполной выборкой (после пагинации). Тема активно обсуждалась в слаке. Сергей Савельев ответил:
 "в этой работе допустимо сортировать в памяти уже после фильтрации и пагинации."

2022-11-27 12:52 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private Long initiator;
Алина, я не Игорь) Я Максим

2022-11-27 12:53 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/NewEventDto.java
> +    private Integer participantLimit;
Выполнено

2022-11-28 09:42 UTC, damirovna commented on ewm-service/src/main/resources/schema.sql
> +    views INT,
Если ваш наставник принимает такое решение, то и я, конечно приму!

2022-11-28 10:03 UTC, damirovna approved these changes
Критических замечаний нет, но нужно исправить упушенные в прошлом ревью замечания перед началом работы над фичей!

2022-11-28 10:03 UTC, damirovna commented on ewm-service/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private List<EventFullDto> setViewsFullDto(List<EventFullDto> events) {
Подумайте чем отличаются методы setViewsFullDto и setViewsShortDto можно ли как-то убрать дублирование в этой ситуации

2022-11-29 09:20 UTC, merged

2022-11-29 16:35 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private int views;
Выполнено

2022-11-29 16:36 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private int confirmedRequests;
выполнено

2022-11-29 16:37 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private String annotation;
выполнено

2022-11-29 16:37 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private String title;
Выполнено

2022-11-29 16:38 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private CategoryDto category;
Выполнено

2022-11-29 16:39 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/dto/EventShortDto.java
> +    private LocalDateTime eventDate;
Выполнено

2022-11-29 16:55 UTC, DenisenkoMax commented on stats-server/src/main/resources/schema.sql
> +    app VARCHAR(50) NOT NULL,
в поле app хранится название приложения, оно в нашем случае для всех записей одинаковое (не уникальное)

2022-11-29 18:15 UTC, DenisenkoMax commented on ewm-service/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private List<EventFullDto> setViewsFullDto(List<EventFullDto> events) {
Исправил